In [6]:
import numpy as np
from scipy.sparse import csr_matrix
dense_matrix = np.array([
    [0, 0, 3, 0],
    [0, 0, 0, 0],
    [5, 0, 0, 0],
    [0, 0, 2, 0]
])

print(dense_matrix)
sparse_matrix=csr_matrix(dense_matrix)
print("Data:", sparse_matrix.data)
print("INDICES:",sparse_matrix.indices)
print("Indptr:",sparse_matrix.indptr)

[[0 0 3 0]
 [0 0 0 0]
 [5 0 0 0]
 [0 0 2 0]]
Data: [3 5 2]
INDICES: [2 0 2]
Indptr: [0 1 1 2 3]


In [9]:
import numpy as np
from scipy.optimize import minimize
def loss_function(x):
    return (x-3)**2
result=minimize(loss_function,x0=0)  
print(result)
print("MINIMUM AT X =",result.x)
print("MINIMUM VALUE =",result.fun)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.5388963550532293e-16
        x: [ 3.000e+00]
      nit: 2
      jac: [-1.697e-08]
 hess_inv: [[ 5.000e-01]]
     nfev: 6
     njev: 3
MINIMUM AT X = [2.99999998]
MINIMUM VALUE = 2.5388963550532293e-16


In [11]:
from scipy.optimize import root
def equation(x):
    return x**2-4
solution=root(equation,x0=1)
print(solution)
print("Root : ",solution.x)
print("Function value",equation(solution.x))

 message: The solution converged.
 success: True
  status: 1
     fun: [ 1.776e-15]
       x: [ 2.000e+00]
  method: hybr
    nfev: 11
    fjac: [[-1.000e+00]]
       r: [-4.000e+00]
     qtf: [ 1.530e-09]
Root :  [2.]
Function value [1.77635684e-15]
